De forma geral será feito um agente que possui observações parciais do ambiente, tendo como objetivo encontrar um caminho até o objetivo.

Como característica do ambiente temos que ele é determinístico, desconhecido, parcialmente observável, suas ações serão dependentes (time-series), estático, suas percepções serão determinísticas e haverá apenas um agente no ambiente (single agent).

Com base nas características do ambiente será construído um agente, sendo um agente baseado em objetivos com representação atômica, ou seja, não haverá estrutura na qual o agente poderá inferir informações, sua única capacidade será, dado um estado, dizer se é o objetivo ou não, sendo esse tipo de agente é chamado busca, (ideal é que esse ambiente fosse totalmente conhecido, depois o tornaremos)

In [1]:
import numpy as np

In [2]:
"""Iremos criar a classe onde a parte abstrata da busca esrará ocorrendo.
Segundo o livro essa estrutura pode ser representada como uma árvore e que em cada nó deve conter o estado do nó 'estado' 
(Como complemoto ao estado adicionamos outro atributo 'local'), 
ação que formou o nó 'acao', o pai do nó atual 'parent', e o 'custo' da raiz até o nó atual.
E por fim além dos atributos precisamos de um método para avançar para os próximos estados 'expandir', no livro está descrito como 
'modelo de transição'"""

class node:

    def __init__(self, estado, local, acao=None, parent=None, custo=0, passo_redundante=[]):
        self.estado = estado
        self.acao = acao
        self.custo = custo
        self.local = local
        self.parent = parent
        self.passo_redundante = passo_redundante
        
    def __repr__(self):
        return "<Node {}>".format(self.estado)
         
# Metodo utilizado para expandir (avançar) para os próximos estados
    def expandir(self, problema):

        return [self.no_filho(problema, acoes)
                for acoes in problema.acoes_pos(self.estado, self.local, self.passo_redundante)]
    
# Esse método será utilizado pelo 'expandir' para realmente demostrar o novo estado
    def no_filho(self, problema, acao):

        proximo_estado = problema.resultado(self.estado, acao, self.local)
        
        if acao == 'cima':
            local = [self.local[0]-1, self.local[1]]
        elif acao == 'baixo':
            local = [self.local[0]+1,self.local[1]]
        elif acao == 'esquerda':
            local = [self.local[0],self.local[1]-1]
        else:
            local = [self.local[0],self.local[1]+1]

        prox_node = node(proximo_estado, local, acao, self, problema.custo_caminho(self.custo))

        return prox_node
    
    """Devido aos parametros inicializados com a classe podemos refazer os passos, então depois de 
    encontrado o objetivo, será feito um caminho inverso demostrando as ações tomadas"""
    def solucao(self):

        return [no.acao for no in self.cam()[::-1][1:]]
    
# Sendo cam o método que irá uxiliar a 'solucao' a fazer o caminho inverso
    def cam(self):

        nodee, ca = self, []
        while nodee:
            ca.append(nodee)
            nodee = nodee.parent
        return(list(ca))

In [3]:
"""Aqui irá acontecer a definição em si do problema, suas regras, possíveis ações, resultado das ações, teste de objetivo, etc.
os metodos e sua construção irá depender muito do problema à ser abordado"""

class caminho:

    def __init__(self, inicial, objetivo):
        self.inicial = inicial
        self.objetivo = objetivo
        dim = inicial.shape
        self.dim = [dim[0]-1, dim[1]-1]

    def custo_caminho(self, c):

        return c+1

    def acoes_pos(self, estado, local, passo_redundante):

        acoes = []

        """Variáveis utilizadas para localização caso o agente esteja cercado por 
        estados já. Permitindo passos redundantes"""
        cnt_sup_dir = 0
        cnt_sup_esq = 0
        cnt_inf_dir = 0
        cnt_inf_esq = 0
        row_sup = 0
        row_inf = 0
        col_esq = 0
        col_dir = 0

        # esta na primeira coluna
        if local[1] == 0:
            col_esq+=1

            # Canto superior esquerdo
            if local == [0,0]:
                cnt_sup_esq+=1

                # testar se veio de baixo
                if estado[local[0]+1][local[1]] != 1:
    
                    acoes.append('baixo')

                # testar se veio da direita
                if estado[local[0]][local[1]+1] != 1:       
         
                    acoes.append('direita')

            # Canto inferior esquerdo
            elif local == [self.dim[0],0]:
                cnt_inf_esq+=1
                        
                # testar se veio de cima
                if estado[local[0]-1][local[1]] != 1:  

                    acoes.append('cima') 

                # testar se veio da direita
                if estado[local[0]][local[1]+1] != 1:       
    
                    acoes.append('direita')

            else:
                col_esq+=1
                # testar se veio de baixo
                if estado[local[0]+1][local[1]] != 1:
            
                    acoes.append('baixo')

                # testar se veio de cima
                if estado[local[0]-1][local[1]] != 1:  
               
                    acoes.append('cima')

                # testar se veio da direita
                if estado[local[0]][local[1]+1] != 1:       
          
                    acoes.append('direita')               
        
        # esta na primeira fileira
        elif local[0] == 0:
            row_sup+=1
                    
            # Canto superior direito
            if local == [0,self.dim[0]]:
                cnt_sup_dir+=1

                # testar se veio de baixo
                if estado[local[0]+1][local[1]] != 1:

                        acoes.append('baixo')

                # testar se veio da esquerda
                if estado[local[0]][local[1]-1] != 1:
                        
                        acoes.append('esquerda')

            # Canto superior esquerdo
            elif local == [0,0]:
                cnt_sup_esq+=1

                # testar se veio de baixo
                if estado[local[0]+1][local[1]] != 1:

                    acoes.append('baixo')

                # testar se veio da direita
                if estado[local[0]][local[1]+1] != 1:       

                    acoes.append('direita')

            else:
           
                # testar se veio de baixo
                if estado[local[0]+1][local[1]] != 1:

                    acoes.append('baixo')

                # testar se veio da esquerda
                if estado[local[0]][local[1]-1] != 1:

                    acoes.append('esquerda')

                # testar se veio da direita
                if estado[local[0]][local[1]+1] != 1:       

                    acoes.append('direita')

        # esta na ultima fileira
        elif local[0] == self.dim[0]:
            row_inf+=1

            # Canto inferior direito
            if local == [self.dim[0],self.dim[1]]:
                cnt_inf_dir+=1

                # testar se veio de cima
                if estado[local[0]-1][local[1]] != 1:  

                    acoes.append('cima')

                # testar se veio da esquerda
                if estado[local[0]][local[1]-1] != 1:

                    acoes.append('esquerda')

            # Canto inferior esquerdo
            elif local == [self.dim[0],0]:
                cnt_inf_esq+=1

                # testar se veio de cima
                if estado[local[0]-1][local[1]] != 1:  

                    acoes.append('cima') 

                # testar se veio da direita
                if estado[local[0]][local[1]+1] != 1:       
 
                    acoes.append('direita')

            else:

                # testar se veio de cima
                if estado[local[0]-1][local[1]] != 1:  

                    acoes.append('cima')
                # testar se veio da esquerda
                if estado[local[0]][local[1]-1] != 1:
                  
                    acoes.append('esquerda')
                # testar se veio da direita
                if estado[local[0]][local[1]+1] != 1:       
                  
                    acoes.append('direita')

        # esta na ultima coluna
        elif local[1] == self.dim[1]:
            col_dir+=1
                                 
            # Canto inferior direito
            if local == [self.dim[0],self.dim[1]]:
                cnt_inf_dir+=1
     
                # testar se veio de cima
                if estado[local[0]-1][local[1]] != 1:  
              
                    acoes.append('cima')

                # testar se veio da esquerda
                if estado[local[0]][local[1]-1] != 1:
                  
                    acoes.append('esquerda')

            # Canto superior direito
            elif local == [0,self.dim[1]]:
                cnt_sup_dir+=1

                # testar se veio de baixo
                if estado[local[0]+1][local[1]] != 1:
                   
                        acoes.append('baixo')

                # testar se veio da esquerda
                if estado[local[0]][local[1]-1] != 1:
                   
                        acoes.append('esquerda')

            else:

                # testar se veio de baixo
                if estado[local[0]+1][local[1]] != 1:
            
                    acoes.append('baixo')

                # testar se veio de cima
                if estado[local[0]-1][local[1]] != 1:  
          
                    acoes.append('cima')

                # testar se veio da esquerda
                if estado[local[0]][local[1]-1] != 1:

                    acoes.append('esquerda')

        else:
                   
            # testar se veio de baixo
            if estado[local[0]+1][local[1]] != 1:

                acoes.append('baixo')
            # testar se veio de cima
            if estado[local[0]-1][local[1]] != 1:  

                acoes.append('cima') 
            # testar se veio da esquerda
            if estado[local[0]][local[1]-1] != 1:

                acoes.append('esquerda')
            # testar se veio da direita
            if estado[local[0]][local[1]+1] != 1:
                
                acoes.append('direita')

        """Caso o agente estaja em um local sercado por 1, ou seja, que já tenham sido visitados
        e pode haver parede. Ele será permitido a fazer um passo redundante, avançando para um local já
        visitado, isso será possível com as variáveis iníciadas no começo do método"""

        if len(acoes) == 0:
            # Iremos adicionar 1 há uma lista, dessa forma iremos saber a quantia de passos redundantes
            passo_redundante.append(1)
          
            if row_sup >= 1:
                
                if cnt_sup_dir >= 1:
                    acoes = ['baixo', 'esquerda']
                elif cnt_sup_esq >= 1:
                    acoes = ['baixo', 'direita']
                else:
                    acoes = ['baixo', 'esquerda', 'direita']

            elif row_inf >= 1:

                if cnt_inf_dir >= 1:
                    acoes = ['cima', 'esquerda']

                elif cnt_inf_esq >= 1:
                    acoes = ['cima', 'direita']

                else:
                    acoes = ['cima', 'esquerda', 'direita']

            elif col_dir >= 1:

                if cnt_inf_dir >= 1:
                    acoes = ['cima', 'esquerda']

                elif cnt_sup_dir >= 1:
                    acoes = ['baixo', 'esquerda']

                else:
                    acoes = ['cima', 'baixo', 'esquerda']

            elif col_esq >= 1:

                if cnt_inf_esq >= 1:
                    acoes = ['cima', 'direita']

                elif cnt_sup_esq >= 1:
                    acoes = ['baixo', 'direita']

                else:
                    acoes = ['cima', 'baixo', 'direita']
                
            else:
                acoes = ['cima', 'baixo', 'esquerda', 'direita']

        return acoes

    # Dado uma ação ira demostrar seu impacto no estado
    def resultado(self, estado, acao, local):

        try:
            estado = estado.copy()
        except:
            estado = estado.estado.copy()
            local = estado.local

        if acao == 'cima':
            estado[local[0]-1][local[1]] = 1

        elif acao == 'baixo':
            estado[local[0]+1][local[1]] = 1

        elif acao == 'esquerda':
            estado[local[0]][local[1]-1] = 1

        elif acao == 'direita':
            estado[local[0]][local[1]+1] = 1

        return estado

    # E por fim será testado se determinado estado é o objetivo
    def teste_objetivo(self, estado):

        if estado[self.objetivo[0]][self.objetivo[1]] == 1:
             return True
        else:
             return False

E por fim, existem alguns algoritimos que podem ser usados para busca em árvores ou grafos. Uma das destinções de um algoritimo para o outro é a forma com a qual ele irá expandir os nós, isso irá afetar em sua performace, essa pode ser mesnurada por 4 métricas.
- Velocidade em que o algoritimo encontrou o objetivo (complexidade de tempo)
- A quantia de espaço que é utilizado (complexidade de espaço)
- Se caso o objetivo pode ser encontrado o algoritimo fará isso com certeza (completude)
- Se esse objetivo encontrado é pelo caminho ótimo (Otimização)

Dessa forma cada algoritimo terá seu ponto forte, sendo mais recomendado dependendo do tipo do problema, e para que está sendo utilizado

In [4]:
"""Esse algoritimo irá expandir o ramo da estrutura até o seu fim, caso chegue e não tenha encontrado o objetivo
será continuado em outro ramo até que o objetivo seja encontrado(supondo que ele pode ser encontrado).
É um algoritimo completo
Não é ótimo (seu caminho encontrado pode não ser o melhor)

"""

def profundidade(prob, local):

    # Lista com os nós expandidos
    folha = [node(prob.inicial, local)] 


    while folha:

        # Irá selecionar o último nó
        no = folha.pop()

        if prob.teste_objetivo(no.estado):
            return no
        
        # Irá expandir a lista de folhas, adicionando as novas no fim
        folha.extend(no.expandir(prob))

    return None

In [5]:
ambiente = np.zeros([10,10])

# Local de início do agente
ambiente[7,6] = 1
problema = caminho(ambiente, objetivo=[3,4])

busca_profundidade = profundidade(problema, [7,6])

print(busca_profundidade.estado)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [6]:
"""Esse algoritimo irá expandir sempre o nó mais curto, ou seja, ele fará seu caminho 
da esquerda para direita para se caso não haver mais nós no nível ir para o próximo

É um algoritimo completo
Caso o custo de caminho for uniforme (Como é o caso) ele será ótimo


"""

def Largura(prob, local):

    # Lista com os nós
    folha = [node(prob.inicial, local)]

    while folha:

        # Uma lista com os nós recem expandidos
        test = folha[0].expandir(prob)
       
        """Há um detalhe no algoritimo que ele fará o teste nos nós recem expandidos
        ao invés de fazer isso na hora que os nós forem expandidos. Isso tem um motivo,
        fazendo isso reduzimos um nível na árvore (sendo esse ultímo nível extramamente custoso)"""
        for i in range(len(test)):

            if prob.teste_objetivo(test[i].estado):
                return test[i]
            
            folha.extend([test[i]])
        # É deletado o primeiro nó da lista desta forma 'test' pegará sempre o "vizinho"    
        folha.remove(folha[0])
      

In [7]:
busca_largura = Largura(problema, [7,6])

print(busca_largura.estado)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
